### ISSUE TITLE
Fails to Compile

### ISSUE THREAD

**Issue by lilithdotgov** [BinaryQuantumSoul/discord-latex#4]
Did a fresh restart of Discord, BD, and the plugin, keep getting this error:
"TypeError: Cannot read properties of undefined (reading 'messageContent')
    at eval (betterdiscord://plugins/LaTeX-remote.plugin.js:12:96)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)"

**Comment by BinaryQuantumSoul** [comment]
Hello I would not call it a "compile" error as it's more like a "runtime" error.

Anyway, the issue is known and latest version is waiting for approval by plugin team. You can already download latest version in `dist/LaTeX.plugin.js`

**Comment by lilithdotgov** [comment]
Thank you for the quick response! Sorry, called it a compiler error as that's the error I was given upon start-up.

**Comment by BinaryQuantumSoul** [comment]
You're welcome:). Don't worry and have fun using the plugin
